version: '3'
services:
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"