version: '3'
services:
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: example
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "9090:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/openapi/webapp-api.json
    volumes:
      - "$PWD/api/openapi-spec:/openapi"
    labels:
      - "traefik.frontend.rule=Host:swagger.docker.localhost"
      - "traefik.port=8080"